# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AuChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AuChat

	# add the Firebase pod for Google Analytics
	pod 'Firebase/Analytics'

	# Firebase Authentication SDK
	pod 'Firebase/Auth'

	# Firebase Firestore SDK
	pod 'Firebase/Firestore'
	
	# Firebase Storage SDK
	pod 'Firebase/Storage'

  target 'AuChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AuChatUITests' do
    # Pods for testing
  end

end
